import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const policy = (await readFile(resolve(root, 'src/path-policy.cjs'), 'utf8')).replace(/\r\n?/gu, '\n')
const template = (await readFile(resolve(root, 'src/client-template.js'), 'utf8')).replace(/\r\n?/gu, '\n')

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces)
  return value.split('\n').map(line => line ? `${prefix}${line}` : '').join('\n')
}

const wrapped = `/** Generated by scripts/build.mjs. Do not edit directly. */
window.__ModuleLoader__.load({
  id: "dsh-plugin-artifact-preview",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    const __artifactPreviewPathPolicyModule = { exports: {} };
    ((module, exports) => {
${indent(policy, 6)}
    })(__artifactPreviewPathPolicyModule, __artifactPreviewPathPolicyModule.exports);
    const __artifactPreviewPathPolicy = __artifactPreviewPathPolicyModule.exports;
${indent(template, 4)}
    return module.exports;
  },
});
`

await writeFile(resolve(root, 'client.js'), wrapped, 'utf8')
console.log(`built ${resolve(root, 'client.js')}`)
