/** Generated by scripts/build.mjs. Do not edit directly. */
window.__ModuleLoader__.load({
  id: "dsh-plugin-artifact-preview",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    const __artifactPreviewPathPolicyModule = { exports: {} };
    ((module, exports) => {
      'use strict'

      const PREVIEW_EXTENSIONS = new Set(['.html', '.htm', '.svg'])

      function reject(reason) {
        return Object.freeze({ disposition: 'reject', reason })
      }

      function classifyProducedPath(value) {
        if (typeof value !== 'string' || value.length === 0 || value.length > 4096) {
          return reject('invalid-path')
        }
        if (value.includes('\0')) return reject('nul-byte')
        if (/^(?:\\\\|\/\/)/u.test(value)) return reject('network-or-device-path')

        const driveAbsolute = /^[A-Za-z]:[\\/]/u.test(value)
        const colonIndexes = [...value.matchAll(/:/gu)].map(match => match.index)
        if (colonIndexes.length > 0 && !(driveAbsolute && colonIndexes.length === 1 && colonIndexes[0] === 1)) {
          return reject('ambiguous-colon')
        }

        const components = value.split(/[\\/]+/u)
        const basename = components.at(-1)
        if (!basename) return reject('empty-basename')
        if (components.some(component => component !== '' && /[. ]$/u.test(component))) {
          return reject('trailing-dot-or-space')
        }

        const dot = basename.lastIndexOf('.')
        const extension = dot < 0 ? '' : basename.slice(dot).replace(/[A-Z]/gu, character => character.toLowerCase())
        if (PREVIEW_EXTENSIONS.has(extension)) {
          return Object.freeze({ disposition: 'preview', extension })
        }
        return Object.freeze({ disposition: 'native' })
      }

      module.exports = { PREVIEW_EXTENSIONS, classifyProducedPath }

    })(__artifactPreviewPathPolicyModule, __artifactPreviewPathPolicyModule.exports);
    const __artifactPreviewPathPolicy = __artifactPreviewPathPolicyModule.exports;
    const React = require('react')
    const { ProducedFiles, producedForClosing } = require('@deepseek-ai/dsh-client-ui-deliverables/client')
    const { classifyProducedPath } = __artifactPreviewPathPolicy

    const h = React.createElement
    const MARKER = 'dsh_tunnel_preview'
    const MARKER_VALUE = 'web'
    const PREVIEW_REQUEST = 'dsh_artifact_preview'
    const WRAPPER_CSP = "default-src 'none'; base-uri 'none'; connect-src 'self'; style-src 'unsafe-inline'; frame-src 'self'; form-action 'none'"
    const ARTIFACT_CSP = "default-src 'none'; base-uri 'none'; connect-src 'none'; img-src data: blob:; media-src data: blob:; font-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; form-action 'none'; frame-src 'none'; child-src 'none'; object-src 'none'; worker-src 'none'"

    function isTunnelPreviewPage() {
      try {
        return new URL(window.location.href).searchParams.get(MARKER) === MARKER_VALUE
      } catch {
        return false
      }
    }

    function translated(zh, en) {
      return /^zh(?:-|$)/iu.test(navigator.language || '') ? zh : en
    }

    function encodePreviewRequest(request) {
      const bytes = new TextEncoder().encode(JSON.stringify(request))
      let binary = ''
      for (const byte of bytes) binary += String.fromCharCode(byte)
      return btoa(binary).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/u, '')
    }

    function decodePreviewRequest(value) {
      try {
        const padded = value.replaceAll('-', '+').replaceAll('_', '/').padEnd(Math.ceil(value.length / 4) * 4, '=')
        const binary = atob(padded)
        const bytes = Uint8Array.from(binary, character => character.charCodeAt(0))
        const request = JSON.parse(new TextDecoder().decode(bytes))
        if (!request || typeof request !== 'object' || Array.isArray(request)) return null
        if (request.kind === 'error' && typeof request.message === 'string') return request
        if (request.kind !== 'preview') return null
        if (typeof request.sessionId !== 'string' || typeof request.producedPath !== 'string') return null
        return request
      } catch {
        return null
      }
    }

    function requestedPreview() {
      const url = new URL(window.location.href)
      const encoded = url.searchParams.get(PREVIEW_REQUEST)
        ?? new URLSearchParams(url.hash.slice(1)).get(PREVIEW_REQUEST)
      return encoded ? decodePreviewRequest(encoded) : null
    }

    function previewUrl(request) {
      const url = new URL(window.location.href)
      url.searchParams.set(MARKER, MARKER_VALUE)
      url.searchParams.set(PREVIEW_REQUEST, encodePreviewRequest(request))
      url.hash = ''
      return url.toString()
    }

    function previewFailure(code) {
      switch (code) {
        case 'file-too-large':
          return translated('文件超过 5 MiB，无法预览。', 'Files larger than 5 MiB cannot be previewed.')
        case 'invalid-utf8':
          return translated('文件不是有效的 UTF-8 文本。', 'The file is not valid UTF-8 text.')
        case 'session-not-found':
        case 'session-root-unavailable':
          return translated('找不到这个会话的文件目录。', 'The session file directory is unavailable.')
        case 'file-unavailable':
          return translated('文件不存在或已无法读取。', 'The file is missing or unavailable.')
        case 'outside-session-root':
        case 'linked-path':
        case 'linked-file':
        case 'invalid-path':
        case 'not-previewable':
          return translated('这个文件无法安全预览。', 'This file cannot be previewed safely.')
        default:
          return translated('预览失败，请重试。', 'Preview failed. Try again.')
      }
    }

    function clearDocument(targetWindow, title) {
      const doc = targetWindow.document
      const meta = doc.createElement('meta')
      meta.httpEquiv = 'Content-Security-Policy'
      meta.content = WRAPPER_CSP
      const charset = doc.createElement('meta')
      charset.charset = 'utf-8'
      const titleNode = doc.createElement('title')
      titleNode.textContent = title
      const style = doc.createElement('style')
      style.textContent = `
        :root { color-scheme: light dark; font-family: system-ui, -apple-system, "Segoe UI", sans-serif; }
        html, body { width: 100%; height: 100%; margin: 0; }
        body { background: Canvas; color: CanvasText; }
        main { min-height: 100%; display: grid; place-items: center; padding: 24px; box-sizing: border-box; }
        .message { max-width: 560px; line-height: 1.6; text-align: center; }
        iframe { width: 100%; height: 100%; border: 0; background: white; }
      `
      doc.head.replaceChildren(meta, charset, titleNode, style)
      doc.body.replaceChildren()
      doc.documentElement.lang = /^zh(?:-|$)/iu.test(navigator.language || '') ? 'zh-CN' : 'en'
      return doc
    }

    function showMessage(targetWindow, title, message) {
      const doc = clearDocument(targetWindow, title)
      const main = doc.createElement('main')
      const text = doc.createElement('div')
      text.className = 'message'
      text.textContent = message
      main.append(text)
      doc.body.append(main)
    }

    function artifactDocument(content) {
      const escapedCsp = ARTIFACT_CSP.replaceAll('&', '&amp;').replaceAll('"', '&quot;')
      return `<meta http-equiv="Content-Security-Policy" content="${escapedCsp}"><meta charset="utf-8">${content}`
    }

    function showArtifact(targetWindow, artifact) {
      const doc = clearDocument(targetWindow, artifact.name)
      const iframe = doc.createElement('iframe')
      iframe.setAttribute('sandbox', 'allow-scripts')
      iframe.setAttribute('referrerpolicy', 'no-referrer')
      iframe.title = artifact.name
      iframe.srcdoc = artifactDocument(artifact.content)
      doc.body.append(iframe)
    }

    function openPreviewPage(request) {
      window.open(previewUrl(request), '_blank', 'noopener,noreferrer')
    }

    function renderPreviewPage(connection, request) {
      if (request.kind === 'error') {
        showMessage(window, translated('无法预览', 'Cannot preview'), request.message)
        return
      }

      showMessage(window, request.producedPath, translated('正在载入预览…', 'Loading preview…'))
      connection.rpc.call('/artifact-preview', 'read', {
        sessionId: request.sessionId,
        producedPath: request.producedPath,
      })
          .then(result => {
            if (!result.ok) {
              showMessage(window, translated('无法预览', 'Cannot preview'), previewFailure(result.error?.code))
              return
            }
            showArtifact(window, result.value)
          })
          .catch(() => {
            showMessage(
              window,
              translated('无法预览', 'Cannot preview'),
              previewFailure('transport'),
            )
          })
    }

    function selectProduced(owner) {
      const paths = producedForClosing(owner.turn.data.get('deliverables'), owner.seq)
      return paths.length > 0 ? paths : null
    }

    function apply(ctx) {
      if (!isTunnelPreviewPage()) return
      const connection = ctx.get('connection')
      const request = requestedPreview()
      if (request) {
        renderPreviewPage(connection, request)
        return
      }

      function TunnelProducedFiles(props) {
        const openFile = producedPath => {
          const policy = classifyProducedPath(producedPath)
          if (policy.disposition === 'native') {
            props.openFile(producedPath)
            return
          }
          if (policy.disposition === 'reject') {
            openPreviewPage({
              kind: 'error',
              message: translated('这个文件路径无法安全打开。', 'This file path cannot be opened safely.'),
            })
            return
          }
          openPreviewPage({ kind: 'preview', sessionId: props.sessionId, producedPath })
        }
        return h(ProducedFiles, { ...props, openFile, isLoopback: false })
      }

      ctx.slots.inject('conversation.chat.turnTail', () => ctx.slots.register({
        name: 'conversation.chat.turnTail',
        priority: -100,
        select: selectProduced,
        locale: 'deliverables',
        inject: () => ({
          isLoopback: false,
          hooks: { hostDescription: connection.hostDescription },
        }),
      }, TunnelProducedFiles))
    }

    exports.inject = ['slots', 'connection']
    exports.apply = apply

    return module.exports;
  },
});
